#pragma once

enum GLOBAL_TYPES
{
    GT_POSITION,
    GT_AMBIENT,
    GT_DIFFUSE,
    GT_SPECULAR,
    GT_EMISSION,
    GT_SHININESS
};

#define POSITION GLOBAL_TYPES::GT_POSITION
#define AMBIENT GLOBAL_TYPES::GT_AMBIENT
#define DIFFUSE GLOBAL_TYPES::GT_DIFFUSE
#define SPECULAR GLOBAL_TYPES::GT_SPECULAR
#define EMISSION GLOBAL_TYPES::GT_EMISSION
#define SHININESS GLOBAL_TYPES::GT_SHININESS

typedef unsigned int TYPES_ENUM;
